### ISSUE TITLE
1.5图小错误

### ISSUE THREAD

**Issue by zsxsoft** [unruledboy/WebFrontEndStack#1]
#### Rendering Engines

Triddent -> Trident (IE)
Opera的Presto是12.17之前的内核，不是基于Blink开发的。[来源](https://dev.opera.com/blog/300-million-users-and-move-to-webkit/)
#### JavaScript Engines

Edge浏览器是Chakra。[来源](https://channel9.msdn.com/Events/WebPlatformSummit/2015/Chakra-The-JavaScript-Engine-that-powers-Microsoft-Edge)

**Comment by unruledboy** [comment]
Triddent这个是手误了

Opera这个我没搞错，"/" 本意是表达之前用的，空间不足难以完整表达而已

Edge这个纯粹是我懒惰罢了

谢谢指正，等一下commit

**Comment by unruledboy** [comment]
@zsxsoft 你想做contributor吗？

**Comment by zsxsoft** [comment]
这个我不介意啊_ (:з」∠)_ 然而好像没有什么比较好的交流手段的样子

**Comment by unruledboy** [comment]
@zsxsoft 加了你到contributor

另外，v1.7发布了

**Comment by zsxsoft** [comment]
@unruledboy 请问邮件收到了吗_ (:з」∠)_
