### ISSUE TITLE
Ionic Framework?

### ISSUE THREAD

**Issue by brianmontanaweb** [unruledboy/WebFrontEndStack#13]
Include Ionic Framework for Mobile App Builders? Or would this become too specific in the landscape of front end?

http://ionicframework.com/

**Comment by unruledboy** [comment]
@zxsoft , what do you think?

**Comment by zsxsoft** [comment]
I'll add it ASAP.

**Comment by unruledboy** [comment]
@brianmontanaweb welcome to the party! let make the project more popular and more front end dev get benefits from it!

**Comment by brianmontanaweb** [comment]
Thanks! I'll proof the project and see if there is anything else that could fit :+1:

**Comment by zsxsoft** [comment]
@unruledboy I noticed you mentioned a wrong person..

**Comment by unruledboy** [comment]
@zsxsoft which one??

**Comment by zsxsoft** [comment]
@unruledboy Look at the second floor.

**Comment by unruledboy** [comment]
@zsxsoft aha... what a coincidence...
