### ISSUE TITLE
url for the technologies

### ISSUE THREAD

**Issue by unruledboy** [unruledboy/WebFrontEndStack#15]
@zsxsoft @brianmontanaweb what do you think about adding url for each technology? for example, like @brianmontanaweb suggested, Iconic has official url as http://ionicframework.com/ so user can quickly navigate.

**Comment by brianmontanaweb** [comment]
Good idea, either a url to the tool or to the information. Like if it's a CSS selector in the project it links to the [MDN selector url](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Getting_started/Selectors) or [W3C selector url.](http://www.w3.org/TR/css3-selectors/)

**Comment by unruledboy** [comment]
@brianmontanaweb agree
@zsxsoft well done, mate!

**Comment by unruledboy** [comment]
I will add url to remaining items later today. guys, feel free to commit
